### ISSUE TITLE
[EPIC] Custom base project

### ISSUE THREAD

**Issue by manununhez** [manununhez/purrfect-pics#1]
This epic will update the base structure created from the Android Studio

- [x] #2
- [x] #3
- [x] #4
- [x] #5

**Comment by manununhez** [comment]
This epic will update the base structure created from the Android Studio

Add theme day/night
Add splashActivity
Add package structure
Add icon app images

**Comment by manununhez** [comment]
This epic will update the base structure created from the Android Studio

- [ ]  Add theme day/night
- [ ]  Add splashActivity
- [ ]  Add package structure
- [ ]  Add icon app
